# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  schedule:
    - cron:  "15 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install --no-root
      - run: poetry run playwright install chromium
      - run: RD_TOKEN=${{secrets.RD_TOKEN}} SUBSCRIBE=${{secrets.SUBSCRIBE}} KMN=${{secrets.KMN}} poetry run python main.py
